export default {

  ZONES_RECIEVED: 'ZONES_RECIEVED',
  ZONES_CREATED: 'ZONES_CREATED',
  SELECT_ZONE: 'SELECT_ZONE',

  COMMENTS_RECIEVED: 'COMMENTS_RECIEVED',
  COMMENTS_CREATED: 'COMMENTS_CREATED',

  CURRENT_USER_RECIEVED: 'CURRENT_USER_RECIEVED'

}
